// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeletePrivateConfig() {
  return window['go']['app']['App']['DeletePrivateConfig']();
}

export function DisarmKillSwitch() {
  return window['go']['app']['App']['DisarmKillSwitch']();
}

export function FastModePresets() {
  return window['go']['app']['App']['FastModePresets']();
}

export function GetAutoStartEnabled() {
  return window['go']['app']['App']['GetAutoStartEnabled']();
}

export function GetCustomDomains() {
  return window['go']['app']['App']['GetCustomDomains']();
}

export function GetExternalIP() {
  return window['go']['app']['App']['GetExternalIP']();
}

export function GetVersion() {
  return window['go']['app']['App']['GetVersion']();
}

export function HasPrivateConfig() {
  return window['go']['app']['App']['HasPrivateConfig']();
}

export function ImportPrivateConfig(arg1) {
  return window['go']['app']['App']['ImportPrivateConfig'](arg1);
}

export function IsElevated() {
  return window['go']['app']['App']['IsElevated']();
}

export function OpenLogsFolder() {
  return window['go']['app']['App']['OpenLogsFolder']();
}

export function Ping() {
  return window['go']['app']['App']['Ping']();
}

export function PrivateConfigSummary() {
  return window['go']['app']['App']['PrivateConfigSummary']();
}

export function Ready() {
  return window['go']['app']['App']['Ready']();
}

export function RequestFastMode(arg1, arg2) {
  return window['go']['app']['App']['RequestFastMode'](arg1, arg2);
}

export function RequestIdle() {
  return window['go']['app']['App']['RequestIdle']();
}

export function RequestPrivateMode() {
  return window['go']['app']['App']['RequestPrivateMode']();
}

export function ResetAndQuit() {
  return window['go']['app']['App']['ResetAndQuit']();
}

export function SaveCustomDomains(arg1) {
  return window['go']['app']['App']['SaveCustomDomains'](arg1);
}

export function SetAutoStart(arg1) {
  return window['go']['app']['App']['SetAutoStart'](arg1);
}

export function SetReconnectOnLaunch(arg1) {
  return window['go']['app']['App']['SetReconnectOnLaunch'](arg1);
}

export function SetTrayUpdater(arg1) {
  return window['go']['app']['App']['SetTrayUpdater'](arg1);
}

export function State() {
  return window['go']['app']['App']['State']();
}

export function Uninstall() {
  return window['go']['app']['App']['Uninstall']();
}

export function VerifyFastModeEngine() {
  return window['go']['app']['App']['VerifyFastModeEngine']();
}

export function VerifyPrivateModeEngine() {
  return window['go']['app']['App']['VerifyPrivateModeEngine']();
}
