// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FastModePresets() {
  return window['go']['app']['App']['FastModePresets']();
}

export function FastModeStrategies() {
  return window['go']['app']['App']['FastModeStrategies']();
}

export function GetAutoStartEnabled() {
  return window['go']['app']['App']['GetAutoStartEnabled']();
}

export function GetCustomDomains() {
  return window['go']['app']['App']['GetCustomDomains']();
}

export function GetVersion() {
  return window['go']['app']['App']['GetVersion']();
}

export function IsElevated() {
  return window['go']['app']['App']['IsElevated']();
}

export function OpenLogsFolder() {
  return window['go']['app']['App']['OpenLogsFolder']();
}

export function Ping() {
  return window['go']['app']['App']['Ping']();
}

export function Ready() {
  return window['go']['app']['App']['Ready']();
}

export function RequestFastMode(arg1, arg2, arg3) {
  return window['go']['app']['App']['RequestFastMode'](arg1, arg2, arg3);
}

export function RequestIdle() {
  return window['go']['app']['App']['RequestIdle']();
}

export function ResetAndQuit() {
  return window['go']['app']['App']['ResetAndQuit']();
}

export function SaveCustomDomains(arg1) {
  return window['go']['app']['App']['SaveCustomDomains'](arg1);
}

export function SetAutoStart(arg1) {
  return window['go']['app']['App']['SetAutoStart'](arg1);
}

export function SetReconnectOnLaunch(arg1) {
  return window['go']['app']['App']['SetReconnectOnLaunch'](arg1);
}

export function SetTrayUpdater(arg1) {
  return window['go']['app']['App']['SetTrayUpdater'](arg1);
}

export function State() {
  return window['go']['app']['App']['State']();
}

export function Uninstall() {
  return window['go']['app']['App']['Uninstall']();
}

export function VerifyFastModeEngine() {
  return window['go']['app']['App']['VerifyFastModeEngine']();
}
