// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetVersion() {
  return window['go']['app']['App']['GetVersion']();
}

export function IsElevated() {
  return window['go']['app']['App']['IsElevated']();
}

export function Ping() {
  return window['go']['app']['App']['Ping']();
}
