// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {fastmode} from '../models';
import {privatemode} from '../models';
import {statemachine} from '../models';

export function DeletePrivateConfig():Promise<void>;

export function DisarmKillSwitch():Promise<void>;

export function FastModePresets():Promise<Record<string, Array<string>>>;

export function FastModeStrategies():Promise<Array<fastmode.StrategyInfo>>;

export function GetAutoStartEnabled():Promise<boolean>;

export function GetCustomDomains():Promise<Array<string>>;

export function GetExternalIP():Promise<string>;

export function GetVersion():Promise<string>;

export function HasPrivateConfig():Promise<boolean>;

export function ImportPrivateConfig(arg1:string):Promise<privatemode.Summary>;

export function IsElevated():Promise<boolean>;

export function OpenLogsFolder():Promise<void>;

export function Ping():Promise<string>;

export function PrivateConfigSummary():Promise<privatemode.Summary>;

export function Ready():Promise<any>;

export function RequestFastMode(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function RequestIdle():Promise<void>;

export function RequestPrivateMode():Promise<void>;

export function ResetAndQuit():Promise<void>;

export function SaveCustomDomains(arg1:Array<string>):Promise<void>;

export function SetAutoStart(arg1:boolean):Promise<void>;

export function SetReconnectOnLaunch(arg1:boolean):Promise<void>;

export function SetTrayUpdater(arg1:any):Promise<void>;

export function State():Promise<statemachine.Status>;

export function Uninstall():Promise<void>;

export function VerifyFastModeEngine():Promise<void>;

export function VerifyPrivateModeEngine():Promise<void>;
